// Generated by Haxe
(function (console, $global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); };
function $extend(from, fields) {
	function Inherit() {} Inherit.prototype = from; var proto = new Inherit();
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var doom_core_IRender = function() { };
doom_core_IRender.__name__ = ["doom","core","IRender"];
var doom_html_Render = function(doc,namespaces) {
	if(null == doc) this.doc = window.document; else this.doc = doc;
	if(null == namespaces) {
		this.namespaces = new haxe_ds_StringMap();
		var tmp = doom_html_Render.defaultNamespaces.keys();
		while(tmp.hasNext()) {
			var key = tmp.next();
			var tmp1;
			var _this = doom_html_Render.defaultNamespaces;
			if(__map_reserved[key] != null) tmp1 = _this.getReserved(key); else tmp1 = _this.h[key];
			var value = tmp1;
			var _this1 = this.namespaces;
			if(__map_reserved[key] != null) _this1.setReserved(key,value); else _this1.h[key] = value;
		}
	} else this.namespaces = namespaces;
	this.nodeToComponent = new haxe_ds_ObjectMap();
	this.componentToNode = new haxe_ds_ObjectMap();
};
doom_html_Render.__name__ = ["doom","html","Render"];
doom_html_Render.__interfaces__ = [doom_core_IRender];
doom_html_Render.setEvent = function(el,name,handler) {
	el["on" + name] = handler;
};
doom_html_Render.prototype = {
	mount: function(node,parent) {
		parent.innerHTML = "";
		var post = [];
		var n = this.generate(node);
		parent.appendChild(n);
		var _g = 0;
		while(_g < post.length) {
			var f = post[_g];
			++_g;
			f();
		}
	}
	,apply: function(node,dom) {
		var post = [];
		this.applyToNode(node,dom,dom.parentElement,post,false);
		var _g = 0;
		while(_g < post.length) {
			var f = post[_g];
			++_g;
			f();
		}
	}
	,generate: function(node) {
		var post = [];
		var dom = this.generateNode(node,post);
		var _g = 0;
		while(_g < post.length) {
			var f = post[_g];
			++_g;
			f();
		}
		return dom;
	}
	,applyToNode: function(node,dom,parent,post,tryUnmount) {
		if(null == node && null == dom) return null; else if(null == node) {
			if(tryUnmount) this.unmountDomComponent(dom);
			parent.removeChild(dom);
			return null;
		} else if(null == dom) {
			var el = this.generateNode(node,post);
			parent.appendChild(el);
			return el;
		}
		switch(node[1]) {
		case 0:
			var children = node[4];
			var attributes = node[3];
			var name = node[2];
			if(tryUnmount) this.unmountDomComponent(dom);
			return this.applyElementToNode(name,attributes,children,dom,parent,post);
		case 1:
			var comment = node[2];
			if(tryUnmount) this.unmountDomComponent(dom);
			return this.applyCommentToNode(comment,dom,parent,post);
		case 2:
			var code = node[2];
			if(tryUnmount) this.unmountDomComponent(dom);
			var node1 = dots_Html.parse(code);
			return this.applyNodeToNode(node1,dom,parent,true);
		case 3:
			var text = node[2];
			if(tryUnmount) this.unmountDomComponent(dom);
			return this.applyTextToNode(text,dom,parent,post);
		case 4:
			var comp = node[2];
			return this.applyComponentToNode(comp,dom,parent,post);
		}
	}
	,applyNodeToNode: function(srcDom,dstDom,parent,tryUnmount) {
		var _g = this;
		if(null == srcDom && null == dstDom) return null; else if(null == srcDom) {
			parent.removeChild(dstDom);
			return null;
		} else if(null == dstDom) {
			parent.appendChild(srcDom);
			return srcDom;
		}
		if(tryUnmount) this.unmountDomComponent(dstDom);
		if(srcDom.nodeType == dstDom.nodeType) {
			if(srcDom.nodeType == 1) {
				var srcEl = srcDom;
				var dstEl = dstDom;
				if(srcEl.tagName == dstEl.tagName) {
					this.applyElementAttributes(srcEl,dstEl);
					thx_Arrays.each(this.zipNodeListAndNodeList(srcEl.childNodes,dstEl.childNodes),function(t) {
						_g.applyNodeToNode(t._0,t._1,dstEl,true);
					});
					return dstDom;
				} else return this.replaceChild(parent,dstDom,srcDom);
			} else if(srcDom.nodeType == 8 || srcDom.nodeType == 3) {
				dstDom.textContent = srcDom.textContent;
				return dstDom;
			} else return this.replaceChild(parent,dstDom,srcDom);
		} else return this.replaceChild(parent,dstDom,srcDom);
	}
	,migrate: function(src,dst) {
		var fields = dst.migrationFields();
		var _g = 0;
		while(_g < fields.length) {
			var field = fields[_g];
			++_g;
			var f = [Reflect.field(src,field)];
			if(Reflect.isFunction(f[0])) {
				f[0] = Reflect.field(dst,field);
				src[field] = (function(f1) {
					return function() {
						var args = arguments;
						f1[0].apply(dst,args);
					};
				})(f);
			} else dst[field] = f[0];
		}
	}
	,applyComponentToNode: function(newComp,dom,parent,post) {
		var oldComp = this.nodeToComponent.h[dom.__id__];
		if(null != oldComp) {
			if(thx_Types.sameType(newComp,oldComp)) {
				this.migrate(newComp,oldComp);
				oldComp.willUpdate();
				post.push($bind(oldComp,oldComp.didUpdate));
				if(oldComp.shouldRender()) {
					var node = oldComp.render();
					return this.applyToNode(node,dom,parent,post,false);
				} else return dom;
			} else {
				oldComp.willUnmount();
				this.nodeToComponent.set(dom,newComp);
				this.componentToNode.remove(oldComp);
				this.componentToNode.set(newComp,dom);
				newComp.willMount();
				var node1 = newComp.render();
				newComp.apply = $bind(this,this.apply);
				var dom1 = this.applyToNode(node1,dom,parent,post,false);
				newComp.node = dom1;
				post.splice(0,0,function() {
					newComp.didMount();
				});
				this.nodeToComponent.set(dom1,newComp);
				this.componentToNode.set(newComp,dom1);
				oldComp.isUnmounted = true;
				oldComp.node = null;
				oldComp.didUnmount();
				return dom1;
			}
		} else {
			newComp.willMount();
			var node2 = newComp.render();
			newComp.apply = $bind(this,this.apply);
			var dom2 = this.applyToNode(node2,dom,parent,post,false);
			newComp.node = dom2;
			post.splice(0,0,function() {
				newComp.didMount();
			});
			this.nodeToComponent.set(dom2,newComp);
			this.componentToNode.set(newComp,dom2);
			return dom2;
		}
	}
	,unmountDomComponent: function(dom) {
		var comp = this.nodeToComponent.h[dom.__id__];
		if(null == comp) return;
		this.unmountComponent(comp);
	}
	,unmountComponent: function(comp) {
		var node = this.componentToNode.h[comp.__id__];
		this.componentToNode.remove(comp);
		this.nodeToComponent.remove(node);
		comp.willUnmount();
		comp.isUnmounted = true;
		comp.node = null;
		comp.didUnmount();
	}
	,applyElementToNode: function(name,attributes,children,dom,parent,post) {
		var _g = this;
		if(dom.nodeType == 1 && dom.tagName == name.toUpperCase()) {
			this.applyNodeAttributes(attributes,dom);
			thx_Arrays.each(this.zipVNodesAndNodeList(children,dom.childNodes),function(t) {
				_g.applyToNode(t._0,t._1,dom,post,true);
			});
			return dom;
		} else {
			var el = this.createElement(name,attributes,children,post);
			return this.replaceChild(parent,dom,el);
		}
	}
	,applyCommentToNode: function(comment,dom,parent,post) {
		if(dom.nodeType == 8) {
			dom.textContent = comment;
			return dom;
		} else {
			var el = this.doc.createComment(comment);
			return this.replaceChild(parent,dom,el);
		}
	}
	,applyTextToNode: function(text,dom,parent,post) {
		if(dom.nodeType == 3) {
			dom.textContent = text;
			return dom;
		} else {
			var el = this.doc.createTextNode(text);
			return this.replaceChild(parent,dom,el);
		}
	}
	,replaceChild: function(parent,oldDom,newDom) {
		if(oldDom == newDom) return newDom;
		parent.replaceChild(newDom,oldDom);
		return newDom;
	}
	,zipVNodesAndNodeList: function(vnodes,children) {
		var len;
		var a = vnodes.length;
		var b = children.length;
		if(a > b) len = a; else len = b;
		var _g = [];
		var _g1 = 0;
		while(_g1 < len) {
			var i = _g1++;
			_g.push({ _0 : vnodes[i], _1 : children[i]});
		}
		return _g;
	}
	,zipNodeListAndNodeList: function(left,right) {
		var len;
		var a = left.length;
		var b = right.length;
		if(a > b) len = a; else len = b;
		var _g = [];
		var _g1 = 0;
		while(_g1 < len) {
			var i = _g1++;
			_g.push({ _0 : left[i], _1 : right[i]});
		}
		return _g;
	}
	,applyElementAttributes: function(srcDom,dstDom) {
		var _g = [];
		var _g2 = 0;
		var _g11 = dstDom.attributes.length;
		while(_g2 < _g11) {
			var i = _g2++;
			_g.push(dstDom.attributes.item(i).name);
		}
		var dstAttrs = thx__$Set_Set_$Impl_$.createString(_g);
		var _g1 = [];
		var _g3 = 0;
		var _g21 = srcDom.attributes.length;
		while(_g3 < _g21) {
			var i1 = _g3++;
			_g1.push(srcDom.attributes.item(i1).name);
		}
		var srcAttrs = thx__$Set_Set_$Impl_$.createString(_g1);
		var result = thx__$Set_Set_$Impl_$.copy(dstAttrs);
		var tmp = $iterator(thx__$Set_Set_$Impl_$)(srcAttrs);
		while(tmp.hasNext()) {
			var item = tmp.next();
			result.remove(item);
		}
		var tmp1 = $iterator(thx__$Set_Set_$Impl_$)(result);
		while(tmp1.hasNext()) {
			var key = tmp1.next();
			dstDom.removeAttribute(key);
		}
		var tmp2 = $iterator(thx__$Set_Set_$Impl_$)(srcAttrs);
		while(tmp2.hasNext()) {
			var key1 = tmp2.next();
			var srcValue = doom_html_Attributes.getAttribute(srcDom,key1);
			var dstValue = doom_html_Attributes.getAttribute(dstDom,key1);
			if(srcValue == dstValue) continue;
			doom_html_Attributes.setDynamicAttribute(dstDom,key1,srcValue);
		}
	}
	,applyNodeAttributes: function(attributes,dom) {
		var _g = [];
		var _g2 = 0;
		var _g11 = dom.attributes.length;
		while(_g2 < _g11) {
			var i = _g2++;
			_g.push(dom.attributes.item(i).name);
		}
		var domAttrs = thx__$Set_Set_$Impl_$.createString(_g);
		var _g1 = [];
		var tmp = attributes.keys();
		while(tmp.hasNext()) {
			var key = tmp.next();
			_g1.push(key);
		}
		var vdomAttrs = thx__$Set_Set_$Impl_$.createString(_g1);
		var result = thx__$Set_Set_$Impl_$.copy(domAttrs);
		var tmp1 = $iterator(thx__$Set_Set_$Impl_$)(vdomAttrs);
		while(tmp1.hasNext()) {
			var item = tmp1.next();
			result.remove(item);
		}
		var tmp2 = $iterator(thx__$Set_Set_$Impl_$)(result);
		while(tmp2.hasNext()) {
			var key1 = tmp2.next();
			dom.removeAttribute(key1);
		}
		var tmp3 = $iterator(thx__$Set_Set_$Impl_$)(vdomAttrs);
		while(tmp3.hasNext()) {
			var key2 = tmp3.next();
			var _g21 = __map_reserved[key2] != null?attributes.getReserved(key2):attributes.h[key2];
			if(_g21 == null) doom_html_Attributes.removeAttribute(dom,key2); else switch(_g21[1]) {
			case 1:
				var s = _g21[2];
				if(null == s || s == "") doom_html_Attributes.removeAttribute(dom,key2); else {
					var s1 = _g21[2];
					doom_html_Attributes.setStringAttribute(dom,key2,s1);
				}
				break;
			case 0:
				var b = _g21[2];
				doom_html_Attributes.toggleBoolAttribute(dom,key2,b);
				break;
			case 2:
				var e = _g21[2];
				doom_html_Render.setEvent(dom,key2,e);
				break;
			}
		}
	}
	,generateNode: function(node,post) {
		switch(node[1]) {
		case 0:
			var children = node[4];
			var attributes = node[3];
			var name = node[2];
			return this.createElement(name,attributes,children,post);
		case 1:
			var comment = node[2];
			return this.doc.createComment(comment);
		case 2:
			var code = node[2];
			return dots_Html.parse(code);
		case 3:
			var text = node[2];
			return this.doc.createTextNode(text);
		case 4:
			var comp = node[2];
			comp.willMount();
			var node1 = comp.render();
			var dom = this.generateNode(node1,post);
			comp.node = dom;
			comp.apply = $bind(this,this.apply);
			post.splice(0,0,function() {
				comp.didMount();
			});
			this.nodeToComponent.set(dom,comp);
			this.componentToNode.set(comp,dom);
			return dom;
		}
	}
	,createElement: function(name,attributes,children,post) {
		var colonPos = name.indexOf(":");
		var el;
		if(colonPos > 0) {
			var prefix = name.substring(0,colonPos);
			var name1 = name.substring(colonPos + 1);
			var tmp;
			var _this = this.namespaces;
			if(__map_reserved[prefix] != null) tmp = _this.getReserved(prefix); else tmp = _this.h[prefix];
			var ns = tmp;
			if(null == ns) throw new thx_Error("element prefix \"" + prefix + "\" is not associated to any namespace. Add the right namespace to Doom.namespaces.",null,{ fileName : "Render.hx", lineNumber : 344, className : "doom.html.Render", methodName : "createElement"});
			el = this.doc.createElementNS(ns,name1);
		} else el = this.doc.createElement(name);
		this.applyNodeAttributes(attributes,el);
		var tmp1 = HxOverrides.iter(children);
		while(tmp1.hasNext()) {
			var child = tmp1.next();
			var n = this.generateNode(child,post);
			el.appendChild(n);
		}
		return el;
	}
	,__class__: doom_html_Render
};
var Doom = function() { };
Doom.__name__ = ["Doom"];
var EReg = function(r,opt) {
	opt = opt.split("u").join("");
	this.r = new RegExp(r,opt);
};
EReg.__name__ = ["EReg"];
EReg.prototype = {
	match: function(s) {
		if(this.r.global) this.r.lastIndex = 0;
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
	,matched: function(n) {
		if(this.r.m != null && n >= 0 && n < this.r.m.length) return this.r.m[n]; else throw new js__$Boot_HaxeError("EReg::matched");
	}
	,__class__: EReg
};
var HxOverrides = function() { };
HxOverrides.__name__ = ["HxOverrides"];
HxOverrides.dateStr = function(date) {
	var m = date.getMonth() + 1;
	var d = date.getDate();
	var h = date.getHours();
	var mi = date.getMinutes();
	var s = date.getSeconds();
	return date.getFullYear() + "-" + (m < 10?"0" + m:"" + m) + "-" + (d < 10?"0" + d:"" + d) + " " + (h < 10?"0" + h:"" + h) + ":" + (mi < 10?"0" + mi:"" + mi) + ":" + (s < 10?"0" + s:"" + s);
};
HxOverrides.cca = function(s,index) {
	var x = s.charCodeAt(index);
	if(x != x) return undefined;
	return x;
};
HxOverrides.substr = function(s,pos,len) {
	if(len == null) len = s.length; else if(len < 0) {
		if(pos == 0) len = s.length + len; else return "";
	}
	if(pos < 0) {
		pos = s.length + pos;
		if(pos < 0) pos = 0;
	}
	return s.substr(pos,len);
};
HxOverrides.indexOf = function(a,obj,i) {
	var len = a.length;
	if(i < 0) {
		i += len;
		if(i < 0) i = 0;
	}
	while(i < len) {
		if(a[i] === obj) return i;
		i++;
	}
	return -1;
};
HxOverrides.remove = function(a,obj) {
	var i = HxOverrides.indexOf(a,obj,0);
	if(i == -1) return false;
	a.splice(i,1);
	return true;
};
HxOverrides.iter = function(a) {
	return { cur : 0, arr : a, hasNext : function() {
		return this.cur < this.arr.length;
	}, next : function() {
		return this.arr[this.cur++];
	}};
};
var Main = function() { };
Main.__name__ = ["Main"];
Main.main = function() {
	var tmp = Main.getFilterFromHash();
	var store = lies_Store.create(function(state,action) {
		return { _0 : todomvc_data_Reducers.todoApp(state,action), _1 : []};
	},{ visibilityFilter : tmp, todos : Main.getTodosFromLocalStorage()});
	var f = function(state1) {
		window.localStorage.setItem("TodoMVC-Doom",JSON.stringify(state1.todos));
	};
	store.subscribe(function(state3,_,_1) {
		f(state3);
	});
	var f1 = function(state2) {
		var tmp1;
		var _g = state2.visibilityFilter;
		switch(_g[1]) {
		case 2:
			tmp1 = "/active";
			break;
		case 1:
			tmp1 = "/completed";
			break;
		default:
			tmp1 = "";
		}
		window.location.hash = tmp1;
	};
	store.subscribe(function(state4,_2,_3) {
		f1(state4);
	});
	var f2 = function(action1) {
		window.console.log(thx_Enums.string(action1));
	};
	store.subscribe(function(_4,_5,action2) {
		f2(action2);
	});
	Doom.browser.mount(doom_core_VNodeImpl.ComponentNode(new todomvc_view_App(store)),dots_Query.find("section.todoapp"));
};
Main.getFilterFromHash = function() {
	var hash = thx_Strings.trimCharsLeft(window.location.hash,"#");
	switch(hash) {
	case "/active":
		return todomvc_data_VisibilityFilter.ShowActive;
	case "/completed":
		return todomvc_data_VisibilityFilter.ShowCompleted;
	default:
		return todomvc_data_VisibilityFilter.ShowAll;
	}
};
Main.getTodosFromLocalStorage = function() {
	var v = window.localStorage.getItem("TodoMVC-Doom");
	if(v != null && v.length > 0) return JSON.parse(v); else return [];
};
Math.__name__ = ["Math"];
var Reflect = function() { };
Reflect.__name__ = ["Reflect"];
Reflect.field = function(o,field) {
	try {
		return o[field];
	} catch( e ) {
		haxe_CallStack.lastException = e;
		return null;
	}
};
Reflect.fields = function(o) {
	var a = [];
	if(o != null) {
		var hasOwnProperty = Object.prototype.hasOwnProperty;
		for( var f in o ) {
		if(f != "__id__" && f != "hx__closures__" && hasOwnProperty.call(o,f)) a.push(f);
		}
	}
	return a;
};
Reflect.isFunction = function(f) {
	return typeof(f) == "function" && !(f.__name__ || f.__ename__);
};
var Std = function() { };
Std.__name__ = ["Std"];
Std.string = function(s) {
	return js_Boot.__string_rec(s,"");
};
Std.parseInt = function(x) {
	var v = parseInt(x,10);
	if(v == 0 && (HxOverrides.cca(x,1) == 120 || HxOverrides.cca(x,1) == 88)) v = parseInt(x);
	if(isNaN(v)) return null;
	return v;
};
var StringBuf = function() {
	this.b = "";
};
StringBuf.__name__ = ["StringBuf"];
StringBuf.prototype = {
	__class__: StringBuf
};
var StringTools = function() { };
StringTools.__name__ = ["StringTools"];
StringTools.isSpace = function(s,pos) {
	var c = HxOverrides.cca(s,pos);
	if(!(c > 8 && c < 14)) return c == 32; else return true;
};
StringTools.ltrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,r)) ++r;
	if(r > 0) return HxOverrides.substr(s,r,l - r); else return s;
};
StringTools.rtrim = function(s) {
	var l = s.length;
	var r = 0;
	while(r < l && StringTools.isSpace(s,l - r - 1)) ++r;
	if(r > 0) return HxOverrides.substr(s,0,l - r); else return s;
};
StringTools.trim = function(s) {
	return StringTools.ltrim(StringTools.rtrim(s));
};
StringTools.replace = function(s,sub,by) {
	return s.split(sub).join(by);
};
var ValueType = { __ename__ : ["ValueType"], __constructs__ : ["TNull","TInt","TFloat","TBool","TObject","TFunction","TClass","TEnum","TUnknown"] };
ValueType.TNull = ["TNull",0];
ValueType.TNull.toString = $estr;
ValueType.TNull.__enum__ = ValueType;
ValueType.TInt = ["TInt",1];
ValueType.TInt.toString = $estr;
ValueType.TInt.__enum__ = ValueType;
ValueType.TFloat = ["TFloat",2];
ValueType.TFloat.toString = $estr;
ValueType.TFloat.__enum__ = ValueType;
ValueType.TBool = ["TBool",3];
ValueType.TBool.toString = $estr;
ValueType.TBool.__enum__ = ValueType;
ValueType.TObject = ["TObject",4];
ValueType.TObject.toString = $estr;
ValueType.TObject.__enum__ = ValueType;
ValueType.TFunction = ["TFunction",5];
ValueType.TFunction.toString = $estr;
ValueType.TFunction.__enum__ = ValueType;
ValueType.TClass = function(c) { var $x = ["TClass",6,c]; $x.__enum__ = ValueType; $x.toString = $estr; return $x; };
ValueType.TEnum = function(e) { var $x = ["TEnum",7,e]; $x.__enum__ = ValueType; $x.toString = $estr; return $x; };
ValueType.TUnknown = ["TUnknown",8];
ValueType.TUnknown.toString = $estr;
ValueType.TUnknown.__enum__ = ValueType;
var Type = function() { };
Type.__name__ = ["Type"];
Type.getClassName = function(c) {
	var a = c.__name__;
	if(a == null) return null;
	return a.join(".");
};
Type.getEnumName = function(e) {
	var a = e.__ename__;
	return a.join(".");
};
Type.createInstance = function(cl,args) {
	var _g = args.length;
	switch(_g) {
	case 0:
		return new cl();
	case 1:
		return new cl(args[0]);
	case 2:
		return new cl(args[0],args[1]);
	case 3:
		return new cl(args[0],args[1],args[2]);
	case 4:
		return new cl(args[0],args[1],args[2],args[3]);
	case 5:
		return new cl(args[0],args[1],args[2],args[3],args[4]);
	case 6:
		return new cl(args[0],args[1],args[2],args[3],args[4],args[5]);
	case 7:
		return new cl(args[0],args[1],args[2],args[3],args[4],args[5],args[6]);
	case 8:
		return new cl(args[0],args[1],args[2],args[3],args[4],args[5],args[6],args[7]);
	default:
		throw new js__$Boot_HaxeError("Too many arguments");
	}
	return null;
};
Type["typeof"] = function(v) {
	var _g = typeof(v);
	switch(_g) {
	case "boolean":
		return ValueType.TBool;
	case "string":
		return ValueType.TClass(String);
	case "number":
		if(Math.ceil(v) == v % 2147483648.0) return ValueType.TInt;
		return ValueType.TFloat;
	case "object":
		if(v == null) return ValueType.TNull;
		var e = v.__enum__;
		if(e != null) return ValueType.TEnum(e);
		var c = js_Boot.getClass(v);
		if(c != null) return ValueType.TClass(c);
		return ValueType.TObject;
	case "function":
		if(v.__name__ || v.__ename__) return ValueType.TObject;
		return ValueType.TFunction;
	case "undefined":
		return ValueType.TNull;
	default:
		return ValueType.TUnknown;
	}
};
Type.enumEq = function(a,b) {
	if(a == b) return true;
	try {
		if(a[0] != b[0]) return false;
		var _g1 = 2;
		var _g = a.length;
		while(_g1 < _g) {
			var i = _g1++;
			if(!Type.enumEq(a[i],b[i])) return false;
		}
		var e = a.__enum__;
		if(e != b.__enum__ || e == null) return false;
	} catch( e1 ) {
		haxe_CallStack.lastException = e1;
		return false;
	}
	return true;
};
var doom_core__$AttributeValue_AttributeValue_$Impl_$ = {};
doom_core__$AttributeValue_AttributeValue_$Impl_$.__name__ = ["doom","core","_AttributeValue","AttributeValue_Impl_"];
doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString = function(s) {
	return doom_core_AttributeValueImpl.StringAttribute(s);
};
doom_core__$AttributeValue_AttributeValue_$Impl_$.fromMap = function(map) {
	var values = [];
	var tmp = map.keys();
	while(tmp.hasNext()) {
		var key = tmp.next();
		if(__map_reserved[key] != null?map.getReserved(key):map.h[key]) values.push(key);
	}
	return doom_core_AttributeValueImpl.StringAttribute(values.join(" "));
};
doom_core__$AttributeValue_AttributeValue_$Impl_$.fromBool = function(b) {
	return doom_core_AttributeValueImpl.BoolAttribute(b);
};
doom_core__$AttributeValue_AttributeValue_$Impl_$.fromHandler = function(f) {
	if(null == f) return doom_core_AttributeValueImpl.BoolAttribute(false); else return doom_core_AttributeValueImpl.EventAttribute(function(e) {
		e.preventDefault();
		f();
	});
};
doom_core__$AttributeValue_AttributeValue_$Impl_$.fromEventHandler = function(f) {
	if(null == f) return doom_core_AttributeValueImpl.BoolAttribute(false); else return doom_core_AttributeValueImpl.EventAttribute(f);
};
var doom_core_AttributeValueImpl = { __ename__ : ["doom","core","AttributeValueImpl"], __constructs__ : ["BoolAttribute","StringAttribute","EventAttribute"] };
doom_core_AttributeValueImpl.BoolAttribute = function(b) { var $x = ["BoolAttribute",0,b]; $x.__enum__ = doom_core_AttributeValueImpl; $x.toString = $estr; return $x; };
doom_core_AttributeValueImpl.StringAttribute = function(s) { var $x = ["StringAttribute",1,s]; $x.__enum__ = doom_core_AttributeValueImpl; $x.toString = $estr; return $x; };
doom_core_AttributeValueImpl.EventAttribute = function(f) { var $x = ["EventAttribute",2,f]; $x.__enum__ = doom_core_AttributeValueImpl; $x.toString = $estr; return $x; };
var doom_core_Component = function(props,children) {
	this.isUnmounted = false;
	this.props = props;
	this.children = children;
};
doom_core_Component.__name__ = ["doom","core","Component"];
doom_core_Component.prototype = {
	render: function() {
		throw new thx_error_AbstractMethod({ fileName : "Component.hx", lineNumber : 16, className : "doom.core.Component", methodName : "render"});
	}
	,asNode: function() {
		return doom_core_VNodeImpl.ComponentNode(this);
	}
	,update: function(props) {
		var old = this.props;
		this.props = props;
		if(!this.shouldUpdate(old,props) || !this.shouldRender()) return;
		this.apply(doom_core_VNodeImpl.ComponentNode(this),this.node);
	}
	,shouldUpdate: function(oldProps,newProps) {
		return true;
	}
	,shouldRender: function() {
		return !this.isUnmounted;
	}
	,migrationFields: function() {
		return ["props","update"];
	}
	,didMount: function() {
	}
	,willMount: function() {
	}
	,willUpdate: function() {
	}
	,didUpdate: function() {
	}
	,didUnmount: function() {
	}
	,willUnmount: function() {
	}
	,__class__: doom_core_Component
};
var doom_core__$VNode_VNode_$Impl_$ = {};
doom_core__$VNode_VNode_$Impl_$.__name__ = ["doom","core","_VNode","VNode_Impl_"];
doom_core__$VNode_VNode_$Impl_$.el = function(name,attributes,children) {
	if(null == attributes) attributes = new haxe_ds_StringMap();
	if(null == children) children = [];
	return doom_core_VNodeImpl.Element(name,attributes,children);
};
var doom_core_VNodeImpl = { __ename__ : ["doom","core","VNodeImpl"], __constructs__ : ["Element","Comment","Raw","Text","ComponentNode"] };
doom_core_VNodeImpl.Element = function(name,attributes,children) { var $x = ["Element",0,name,attributes,children]; $x.__enum__ = doom_core_VNodeImpl; $x.toString = $estr; return $x; };
doom_core_VNodeImpl.Comment = function(comment) { var $x = ["Comment",1,comment]; $x.__enum__ = doom_core_VNodeImpl; $x.toString = $estr; return $x; };
doom_core_VNodeImpl.Raw = function(code) { var $x = ["Raw",2,code]; $x.__enum__ = doom_core_VNodeImpl; $x.toString = $estr; return $x; };
doom_core_VNodeImpl.Text = function(text) { var $x = ["Text",3,text]; $x.__enum__ = doom_core_VNodeImpl; $x.toString = $estr; return $x; };
doom_core_VNodeImpl.ComponentNode = function(comp) { var $x = ["ComponentNode",4,comp]; $x.__enum__ = doom_core_VNodeImpl; $x.toString = $estr; return $x; };
var doom_html_AttributeType = { __ename__ : ["doom","html","AttributeType"], __constructs__ : ["BooleanAttribute","Property","BooleanProperty","OverloadedBooleanAttribute","NumericAttribute","PositiveNumericAttribute","SideEffectProperty"] };
doom_html_AttributeType.BooleanAttribute = ["BooleanAttribute",0];
doom_html_AttributeType.BooleanAttribute.toString = $estr;
doom_html_AttributeType.BooleanAttribute.__enum__ = doom_html_AttributeType;
doom_html_AttributeType.Property = ["Property",1];
doom_html_AttributeType.Property.toString = $estr;
doom_html_AttributeType.Property.__enum__ = doom_html_AttributeType;
doom_html_AttributeType.BooleanProperty = ["BooleanProperty",2];
doom_html_AttributeType.BooleanProperty.toString = $estr;
doom_html_AttributeType.BooleanProperty.__enum__ = doom_html_AttributeType;
doom_html_AttributeType.OverloadedBooleanAttribute = ["OverloadedBooleanAttribute",3];
doom_html_AttributeType.OverloadedBooleanAttribute.toString = $estr;
doom_html_AttributeType.OverloadedBooleanAttribute.__enum__ = doom_html_AttributeType;
doom_html_AttributeType.NumericAttribute = ["NumericAttribute",4];
doom_html_AttributeType.NumericAttribute.toString = $estr;
doom_html_AttributeType.NumericAttribute.__enum__ = doom_html_AttributeType;
doom_html_AttributeType.PositiveNumericAttribute = ["PositiveNumericAttribute",5];
doom_html_AttributeType.PositiveNumericAttribute.toString = $estr;
doom_html_AttributeType.PositiveNumericAttribute.__enum__ = doom_html_AttributeType;
doom_html_AttributeType.SideEffectProperty = ["SideEffectProperty",6];
doom_html_AttributeType.SideEffectProperty.toString = $estr;
doom_html_AttributeType.SideEffectProperty.__enum__ = doom_html_AttributeType;
var doom_html_Attributes = function() { };
doom_html_Attributes.__name__ = ["doom","html","Attributes"];
doom_html_Attributes.getAttribute = function(el,name) {
	var tmp;
	var _this = doom_html_Attributes.properties;
	if(__map_reserved[name] != null) tmp = _this.getReserved(name); else tmp = _this.h[name];
	var prop = tmp;
	if(prop == null) return el.getAttribute(name); else switch(prop[1]) {
	case 0:case 3:case 4:case 5:
		return el.getAttribute(name);
	case 1:case 2:case 6:
		return Reflect.field(el,name);
	}
};
doom_html_Attributes.setDynamicAttribute = function(el,name,value) {
	var tmp;
	var _this = doom_html_Attributes.properties;
	if(__map_reserved[name] != null) tmp = _this.getReserved(name); else tmp = _this.h[name];
	var prop = tmp;
	if(prop == null) el.setAttribute(name,value); else switch(prop[1]) {
	case 0:case 3:case 4:case 5:
		el.setAttribute(name,value);
		break;
	case 1:case 2:case 6:
		el[name] = value;
		break;
	}
	return;
};
doom_html_Attributes.setStringAttribute = function(el,name,value) {
	var tmp;
	var _this = doom_html_Attributes.properties;
	if(__map_reserved[name] != null) tmp = _this.getReserved(name); else tmp = _this.h[name];
	var prop = tmp;
	if(prop == null) el.setAttribute(name,value); else switch(prop[1]) {
	case 0:case 3:case 4:case 5:
		el.setAttribute(name,value);
		break;
	case 1:case 2:case 6:
		el[name] = value;
		break;
	}
	return;
};
doom_html_Attributes.toggleBoolAttribute = function(el,name,value) {
	var tmp;
	var _this = doom_html_Attributes.properties;
	if(__map_reserved[name] != null) tmp = _this.getReserved(name); else tmp = _this.h[name];
	var prop = tmp;
	if(prop == null) {
		if(value) el.setAttribute(name,name); else el.removeAttribute(name);
	} else switch(prop[1]) {
	case 0:case 3:case 4:case 5:
		if(value) el.setAttribute(name,name); else el.removeAttribute(name);
		break;
	case 1:case 2:case 6:
		el[name] = value;
		break;
	}
	return;
};
doom_html_Attributes.removeAttribute = function(el,name) {
	el.removeAttribute(name);
};
var doom_html_Component = function(props,children) {
	doom_core_Component.call(this,props,children);
};
doom_html_Component.__name__ = ["doom","html","Component"];
doom_html_Component.__super__ = doom_core_Component;
doom_html_Component.prototype = $extend(doom_core_Component.prototype,{
	__class__: doom_html_Component
});
var dots_Html = function() { };
dots_Html.__name__ = ["dots","Html"];
dots_Html.parseNodes = function(html) {
	if(!dots_Html.pattern.match(html)) throw new js__$Boot_HaxeError("Invalid pattern \"" + html + "\"");
	var el;
	var _g = dots_Html.pattern.matched(1).toLowerCase();
	switch(_g) {
	case "tbody":case "thead":
		el = window.document.createElement("table");
		break;
	case "td":case "th":
		el = window.document.createElement("tr");
		break;
	case "tr":
		el = window.document.createElement("tbody");
		break;
	default:
		el = window.document.createElement("div");
	}
	el.innerHTML = html;
	return el.childNodes;
};
dots_Html.parse = function(html) {
	var nodes = dots_Html.parseNodes(html);
	if(nodes.length > 1) {
		var doc = window.document.createDocumentFragment();
		while(nodes.length > 0) doc.appendChild(nodes[0]);
		return doc;
	} else return nodes[0];
};
var dots_Query = function() { };
dots_Query.__name__ = ["dots","Query"];
dots_Query.find = function(selector,ctx) {
	return (ctx != null?ctx:dots_Query.doc).querySelector(selector);
};
var haxe_StackItem = { __ename__ : ["haxe","StackItem"], __constructs__ : ["CFunction","Module","FilePos","Method","LocalFunction"] };
haxe_StackItem.CFunction = ["CFunction",0];
haxe_StackItem.CFunction.toString = $estr;
haxe_StackItem.CFunction.__enum__ = haxe_StackItem;
haxe_StackItem.Module = function(m) { var $x = ["Module",1,m]; $x.__enum__ = haxe_StackItem; $x.toString = $estr; return $x; };
haxe_StackItem.FilePos = function(s,file,line) { var $x = ["FilePos",2,s,file,line]; $x.__enum__ = haxe_StackItem; $x.toString = $estr; return $x; };
haxe_StackItem.Method = function(classname,method) { var $x = ["Method",3,classname,method]; $x.__enum__ = haxe_StackItem; $x.toString = $estr; return $x; };
haxe_StackItem.LocalFunction = function(v) { var $x = ["LocalFunction",4,v]; $x.__enum__ = haxe_StackItem; $x.toString = $estr; return $x; };
var haxe_CallStack = function() { };
haxe_CallStack.__name__ = ["haxe","CallStack"];
haxe_CallStack.getStack = function(e) {
	if(e == null) return [];
	var oldValue = Error.prepareStackTrace;
	Error.prepareStackTrace = function(error,callsites) {
		var stack = [];
		var _g = 0;
		while(_g < callsites.length) {
			var site = callsites[_g];
			++_g;
			if(haxe_CallStack.wrapCallSite != null) site = haxe_CallStack.wrapCallSite(site);
			var method = null;
			var fullName = site.getFunctionName();
			if(fullName != null) {
				var idx = fullName.lastIndexOf(".");
				if(idx >= 0) {
					var className = HxOverrides.substr(fullName,0,idx);
					var methodName = HxOverrides.substr(fullName,idx + 1,null);
					method = haxe_StackItem.Method(className,methodName);
				}
			}
			stack.push(haxe_StackItem.FilePos(method,site.getFileName(),site.getLineNumber()));
		}
		return stack;
	};
	var a = haxe_CallStack.makeStack(e.stack);
	Error.prepareStackTrace = oldValue;
	return a;
};
haxe_CallStack.callStack = function() {
	try {
		throw new Error();
	} catch( e ) {
		haxe_CallStack.lastException = e;
		if (e instanceof js__$Boot_HaxeError) e = e.val;
		var a = haxe_CallStack.getStack(e);
		a.shift();
		return a;
	}
};
haxe_CallStack.exceptionStack = function() {
	return haxe_CallStack.getStack(haxe_CallStack.lastException);
};
haxe_CallStack.toString = function(stack) {
	var b = new StringBuf();
	var _g = 0;
	while(_g < stack.length) {
		var s = stack[_g];
		++_g;
		b.b += "\nCalled from ";
		haxe_CallStack.itemToString(b,s);
	}
	return b.b;
};
haxe_CallStack.itemToString = function(b,s) {
	switch(s[1]) {
	case 0:
		b.b += "a C function";
		break;
	case 1:
		var m = s[2];
		b.b += "module ";
		b.b += m == null?"null":"" + m;
		break;
	case 2:
		var line = s[4];
		var file = s[3];
		var s1 = s[2];
		if(s1 != null) {
			haxe_CallStack.itemToString(b,s1);
			b.b += " (";
		}
		b.b += file == null?"null":"" + file;
		b.b += " line ";
		b.b += line == null?"null":"" + line;
		if(s1 != null) b.b += ")";
		break;
	case 3:
		var meth = s[3];
		var cname = s[2];
		b.b += cname == null?"null":"" + cname;
		b.b += ".";
		b.b += meth == null?"null":"" + meth;
		break;
	case 4:
		var n = s[2];
		b.b += "local function #";
		b.b += n == null?"null":"" + n;
		break;
	}
};
haxe_CallStack.makeStack = function(s) {
	if(s == null) return []; else if(typeof(s) == "string") {
		var stack = s.split("\n");
		if(stack[0] == "Error") stack.shift();
		var m = [];
		var rie10 = new EReg("^   at ([A-Za-z0-9_. ]+) \\(([^)]+):([0-9]+):([0-9]+)\\)$","");
		var _g = 0;
		while(_g < stack.length) {
			var line = stack[_g];
			++_g;
			if(rie10.match(line)) {
				var path = rie10.matched(1).split(".");
				var meth = path.pop();
				var file = rie10.matched(2);
				var line1 = Std.parseInt(rie10.matched(3));
				m.push(haxe_StackItem.FilePos(meth == "Anonymous function"?haxe_StackItem.LocalFunction():meth == "Global code"?null:haxe_StackItem.Method(path.join("."),meth),file,line1));
			} else m.push(haxe_StackItem.Module(StringTools.trim(line)));
		}
		return m;
	} else return s;
};
var haxe_IMap = function() { };
haxe_IMap.__name__ = ["haxe","IMap"];
haxe_IMap.prototype = {
	__class__: haxe_IMap
};
var haxe_ds_ObjectMap = function() {
	this.h = { __keys__ : { }};
};
haxe_ds_ObjectMap.__name__ = ["haxe","ds","ObjectMap"];
haxe_ds_ObjectMap.__interfaces__ = [haxe_IMap];
haxe_ds_ObjectMap.prototype = {
	set: function(key,value) {
		var id = key.__id__ || (key.__id__ = ++haxe_ds_ObjectMap.count);
		this.h[id] = value;
		this.h.__keys__[id] = key;
	}
	,get: function(key) {
		return this.h[key.__id__];
	}
	,remove: function(key) {
		var id = key.__id__;
		if(this.h.__keys__[id] == null) return false;
		delete(this.h[id]);
		delete(this.h.__keys__[id]);
		return true;
	}
	,keys: function() {
		var a = [];
		for( var key in this.h.__keys__ ) {
		if(this.h.hasOwnProperty(key)) a.push(this.h.__keys__[key]);
		}
		return HxOverrides.iter(a);
	}
	,__class__: haxe_ds_ObjectMap
};
var haxe_ds_Option = { __ename__ : ["haxe","ds","Option"], __constructs__ : ["Some","None"] };
haxe_ds_Option.Some = function(v) { var $x = ["Some",0,v]; $x.__enum__ = haxe_ds_Option; $x.toString = $estr; return $x; };
haxe_ds_Option.None = ["None",1];
haxe_ds_Option.None.toString = $estr;
haxe_ds_Option.None.__enum__ = haxe_ds_Option;
var haxe_ds_StringMap = function() {
	this.h = { };
};
haxe_ds_StringMap.__name__ = ["haxe","ds","StringMap"];
haxe_ds_StringMap.__interfaces__ = [haxe_IMap];
haxe_ds_StringMap.prototype = {
	set: function(key,value) {
		if(__map_reserved[key] != null) this.setReserved(key,value); else this.h[key] = value;
	}
	,get: function(key) {
		if(__map_reserved[key] != null) return this.getReserved(key);
		return this.h[key];
	}
	,setReserved: function(key,value) {
		if(this.rh == null) this.rh = { };
		this.rh["$" + key] = value;
	}
	,getReserved: function(key) {
		if(this.rh == null) return null; else return this.rh["$" + key];
	}
	,remove: function(key) {
		if(__map_reserved[key] != null) {
			key = "$" + key;
			if(this.rh == null || !this.rh.hasOwnProperty(key)) return false;
			delete(this.rh[key]);
			return true;
		} else {
			if(!this.h.hasOwnProperty(key)) return false;
			delete(this.h[key]);
			return true;
		}
	}
	,keys: function() {
		return HxOverrides.iter(this.arrayKeys());
	}
	,arrayKeys: function() {
		var out = [];
		for( var key in this.h ) {
		if(this.h.hasOwnProperty(key)) out.push(key);
		}
		if(this.rh != null) {
			for( var key in this.rh ) {
			if(key.charCodeAt(0) == 36) out.push(key.substr(1));
			}
		}
		return out;
	}
	,__class__: haxe_ds_StringMap
};
var js__$Boot_HaxeError = function(val) {
	Error.call(this);
	this.val = val;
	this.message = String(val);
	if(Error.captureStackTrace) Error.captureStackTrace(this,js__$Boot_HaxeError);
};
js__$Boot_HaxeError.__name__ = ["js","_Boot","HaxeError"];
js__$Boot_HaxeError.__super__ = Error;
js__$Boot_HaxeError.prototype = $extend(Error.prototype,{
	__class__: js__$Boot_HaxeError
});
var js_Boot = function() { };
js_Boot.__name__ = ["js","Boot"];
js_Boot.getClass = function(o) {
	if((o instanceof Array) && o.__enum__ == null) return Array; else {
		var cl = o.__class__;
		if(cl != null) return cl;
		var name = js_Boot.__nativeClassName(o);
		if(name != null) return js_Boot.__resolveNativeClass(name);
		return null;
	}
};
js_Boot.__string_rec = function(o,s) {
	if(o == null) return "null";
	if(s.length >= 5) return "<...>";
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) t = "object";
	switch(t) {
	case "object":
		if(o instanceof Array) {
			if(o.__enum__) {
				if(o.length == 2) return o[0];
				var str2 = o[0] + "(";
				s += "\t";
				var _g1 = 2;
				var _g = o.length;
				while(_g1 < _g) {
					var i1 = _g1++;
					if(i1 != 2) str2 += "," + js_Boot.__string_rec(o[i1],s); else str2 += js_Boot.__string_rec(o[i1],s);
				}
				return str2 + ")";
			}
			var l = o.length;
			var i;
			var str1 = "[";
			s += "\t";
			var _g2 = 0;
			while(_g2 < l) {
				var i2 = _g2++;
				str1 += (i2 > 0?",":"") + js_Boot.__string_rec(o[i2],s);
			}
			str1 += "]";
			return str1;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( e ) {
			haxe_CallStack.lastException = e;
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") return s2;
		}
		var k = null;
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		for( var k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) str += ", \n";
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "function":
		return "<function>";
	case "string":
		return o;
	default:
		return String(o);
	}
};
js_Boot.__interfLoop = function(cc,cl) {
	if(cc == null) return false;
	if(cc == cl) return true;
	var intf = cc.__interfaces__;
	if(intf != null) {
		var _g1 = 0;
		var _g = intf.length;
		while(_g1 < _g) {
			var i = _g1++;
			var i1 = intf[i];
			if(i1 == cl || js_Boot.__interfLoop(i1,cl)) return true;
		}
	}
	return js_Boot.__interfLoop(cc.__super__,cl);
};
js_Boot.__instanceof = function(o,cl) {
	if(cl == null) return false;
	switch(cl) {
	case Int:
		return (o|0) === o;
	case Float:
		return typeof(o) == "number";
	case Bool:
		return typeof(o) == "boolean";
	case String:
		return typeof(o) == "string";
	case Array:
		return (o instanceof Array) && o.__enum__ == null;
	case Dynamic:
		return true;
	default:
		if(o != null) {
			if(typeof(cl) == "function") {
				if(o instanceof cl) return true;
				if(js_Boot.__interfLoop(js_Boot.getClass(o),cl)) return true;
			} else if(typeof(cl) == "object" && js_Boot.__isNativeObj(cl)) {
				if(o instanceof cl) return true;
			}
		} else return false;
		if(cl == Class && o.__name__ != null) return true;
		if(cl == Enum && o.__ename__ != null) return true;
		return o.__enum__ == cl;
	}
};
js_Boot.__nativeClassName = function(o) {
	var name = js_Boot.__toStr.call(o).slice(8,-1);
	if(name == "Object" || name == "Function" || name == "Math" || name == "JSON") return null;
	return name;
};
js_Boot.__isNativeObj = function(o) {
	return js_Boot.__nativeClassName(o) != null;
};
js_Boot.__resolveNativeClass = function(name) {
	return $global[name];
};
var js_html_compat_ArrayBuffer = function(a) {
	if((a instanceof Array) && a.__enum__ == null) {
		this.a = a;
		this.byteLength = a.length;
	} else {
		var len = a;
		this.a = [];
		var _g = 0;
		while(_g < len) {
			var i = _g++;
			this.a[i] = 0;
		}
		this.byteLength = len;
	}
};
js_html_compat_ArrayBuffer.__name__ = ["js","html","compat","ArrayBuffer"];
js_html_compat_ArrayBuffer.sliceImpl = function(begin,end) {
	var u = new Uint8Array(this,begin,end == null?null:end - begin);
	var result = new ArrayBuffer(u.byteLength);
	var resultArray = new Uint8Array(result);
	resultArray.set(u);
	return result;
};
js_html_compat_ArrayBuffer.prototype = {
	slice: function(begin,end) {
		return new js_html_compat_ArrayBuffer(this.a.slice(begin,end));
	}
	,__class__: js_html_compat_ArrayBuffer
};
var js_html_compat_Uint8Array = function() { };
js_html_compat_Uint8Array.__name__ = ["js","html","compat","Uint8Array"];
js_html_compat_Uint8Array._new = function(arg1,offset,length) {
	var arr;
	if(typeof(arg1) == "number") {
		arr = [];
		var _g = 0;
		while(_g < arg1) {
			var i = _g++;
			arr[i] = 0;
		}
		arr.byteLength = arr.length;
		arr.byteOffset = 0;
		arr.buffer = new js_html_compat_ArrayBuffer(arr);
	} else if(js_Boot.__instanceof(arg1,js_html_compat_ArrayBuffer)) {
		var buffer = arg1;
		if(offset == null) offset = 0;
		if(length == null) length = buffer.byteLength - offset;
		if(offset == 0) arr = buffer.a; else arr = buffer.a.slice(offset,offset + length);
		arr.byteLength = arr.length;
		arr.byteOffset = offset;
		arr.buffer = buffer;
	} else if((arg1 instanceof Array) && arg1.__enum__ == null) {
		arr = arg1.slice();
		arr.byteLength = arr.length;
		arr.byteOffset = 0;
		arr.buffer = new js_html_compat_ArrayBuffer(arr);
	} else throw new js__$Boot_HaxeError("TODO " + Std.string(arg1));
	arr.subarray = js_html_compat_Uint8Array._subarray;
	arr.set = js_html_compat_Uint8Array._set;
	return arr;
};
js_html_compat_Uint8Array._set = function(arg,offset) {
	var t = this;
	if((function($this) {
		var $r;
		var v = arg.buffer;
		$r = js_Boot.__instanceof(v,js_html_compat_ArrayBuffer);
		return $r;
	}(this))) {
		var a = arg;
		if(arg.byteLength + offset > t.byteLength) throw new js__$Boot_HaxeError("set() outside of range");
		var _g1 = 0;
		var _g = arg.byteLength;
		while(_g1 < _g) {
			var i = _g1++;
			t[i + offset] = a[i];
		}
	} else if((arg instanceof Array) && arg.__enum__ == null) {
		var a1 = arg;
		if(a1.length + offset > t.byteLength) throw new js__$Boot_HaxeError("set() outside of range");
		var _g11 = 0;
		var _g2 = a1.length;
		while(_g11 < _g2) {
			var i1 = _g11++;
			t[i1 + offset] = a1[i1];
		}
	} else throw new js__$Boot_HaxeError("TODO");
};
js_html_compat_Uint8Array._subarray = function(start,end) {
	var t = this;
	var a = js_html_compat_Uint8Array._new(t.slice(start,end));
	a.byteOffset = start;
	return a;
};
var lies_Store = function(reducer,initialState) {
	this.state = initialState;
	this.reducer = reducer;
	this.listeners = [];
};
lies_Store.__name__ = ["lies","Store"];
lies_Store.create = function(reducer,initialState) {
	return new lies_Store(reducer,initialState);
};
lies_Store.prototype = {
	dispatch: function(action) {
		if(null == action) throw new thx_Error("cannot dispatch a null action",null,{ fileName : "Store.hx", lineNumber : 20, className : "lies.Store", methodName : "dispatch"});
		var oldState = this.state;
		var value = this.reducer(oldState,action);
		this.state = value._0;
		this.invokeListeners(this.state,oldState,action);
		var _g = 0;
		var _g1 = value._1;
		while(_g < _g1.length) {
			var future = _g1[_g];
			++_g;
			future.then($bind(this,this.dispatch));
		}
	}
	,invokeListeners: function(currentState,oldState,action) {
		var _g = 0;
		var _g1 = this.listeners.slice();
		while(_g < _g1.length) {
			var listener = _g1[_g];
			++_g;
			listener(currentState,oldState,action);
		}
	}
	,subscribe: function(listener) {
		var _g = this;
		HxOverrides.remove(this.listeners,listener);
		this.listeners.push(listener);
		return function() {
			HxOverrides.remove(_g.listeners,listener);
		};
	}
	,__class__: lies_Store
};
var thx_Arrays = function() { };
thx_Arrays.__name__ = ["thx","Arrays"];
thx_Arrays.each = function(arr,effect) {
	var tmp = HxOverrides.iter(arr);
	while(tmp.hasNext()) {
		var element = tmp.next();
		effect(element);
	}
};
thx_Arrays.all = function(arr,predicate) {
	var tmp = HxOverrides.iter(arr);
	while(tmp.hasNext()) {
		var element = tmp.next();
		if(!predicate(element)) return false;
	}
	return true;
};
thx_Arrays.findIndex = function(array,predicate) {
	var _g1 = 0;
	var _g = array.length;
	while(_g1 < _g) {
		var i = _g1++;
		if(predicate(array[i])) return i;
	}
	return -1;
};
thx_Arrays.string = function(arr) {
	return "[" + arr.map(thx_Dynamics.string).join(", ") + "]";
};
var thx_Dynamics = function() { };
thx_Dynamics.__name__ = ["thx","Dynamics"];
thx_Dynamics.string = function(v) {
	var _g = Type["typeof"](v);
	switch(_g[1]) {
	case 0:
		return "null";
	case 1:case 2:case 3:
		return "" + Std.string(v);
	case 4:
		return thx_Objects.string(v);
	case 6:
		var c = _g[2];
		var _g1 = Type.getClassName(c);
		switch(_g1) {
		case "Array":
			return thx_Arrays.string(v);
		case "String":
			return v;
		case "Date":
			return HxOverrides.dateStr(v);
		default:
			if(js_Boot.__instanceof(v,haxe_IMap)) return thx_Maps.string(v); else return Std.string(v);
		}
		break;
	case 7:
		return thx_Enums.string(v);
	case 8:
		return "<unknown>";
	case 5:
		return "<function>";
	}
};
var thx_Either = { __ename__ : ["thx","Either"], __constructs__ : ["Left","Right"] };
thx_Either.Left = function(value) { var $x = ["Left",0,value]; $x.__enum__ = thx_Either; $x.toString = $estr; return $x; };
thx_Either.Right = function(value) { var $x = ["Right",1,value]; $x.__enum__ = thx_Either; $x.toString = $estr; return $x; };
var thx_Enums = function() { };
thx_Enums.__name__ = ["thx","Enums"];
thx_Enums.string = function(e) {
	var cons = e[0];
	var params = [];
	var _g = 0;
	var _g1 = e.slice(2);
	while(_g < _g1.length) {
		var param = _g1[_g];
		++_g;
		params.push(thx_Dynamics.string(param));
	}
	return cons + (params.length == 0?"":"(" + params.join(", ") + ")");
};
var thx_Error = function(message,stack,pos) {
	Error.call(this,message);
	this.message = message;
	if(null == stack) {
		try {
			stack = haxe_CallStack.exceptionStack();
		} catch( e ) {
			haxe_CallStack.lastException = e;
			stack = [];
		}
		if(stack.length == 0) try {
			stack = haxe_CallStack.callStack();
		} catch( e1 ) {
			haxe_CallStack.lastException = e1;
			stack = [];
		}
	}
	this.stackItems = stack;
	this.pos = pos;
};
thx_Error.__name__ = ["thx","Error"];
thx_Error.__super__ = Error;
thx_Error.prototype = $extend(Error.prototype,{
	toString: function() {
		return this.message + "\nfrom: " + this.getPosition() + "\n\n" + this.stackToString();
	}
	,getPosition: function() {
		return this.pos.className + "." + this.pos.methodName + "() at " + this.pos.lineNumber;
	}
	,stackToString: function() {
		return haxe_CallStack.toString(this.stackItems);
	}
	,__class__: thx_Error
});
var thx_Iterators = function() { };
thx_Iterators.__name__ = ["thx","Iterators"];
thx_Iterators.map = function(it,f) {
	var acc = [];
	while(it.hasNext()) {
		var v = it.next();
		acc.push(f(v));
	}
	return acc;
};
var thx_Maps = function() { };
thx_Maps.__name__ = ["thx","Maps"];
thx_Maps.tuples = function(map) {
	return thx_Iterators.map(map.keys(),function(key) {
		return { _0 : key, _1 : map.get(key)};
	});
};
thx_Maps.string = function(m) {
	return "[" + thx_Maps.tuples(m).map(function(t) {
		return thx_Dynamics.string(t._0) + " => " + thx_Dynamics.string(t._1);
	}).join(", ") + "]";
};
var thx_Objects = function() { };
thx_Objects.__name__ = ["thx","Objects"];
thx_Objects.combine = function(first,second) {
	var to = { };
	var _g = 0;
	var _g1 = Reflect.fields(first);
	while(_g < _g1.length) {
		var field = _g1[_g];
		++_g;
		to[field] = Reflect.field(first,field);
	}
	var _g2 = 0;
	var _g11 = Reflect.fields(second);
	while(_g2 < _g11.length) {
		var field1 = _g11[_g2];
		++_g2;
		to[field1] = Reflect.field(second,field1);
	}
	return to;
};
thx_Objects.string = function(o) {
	return "{" + Reflect.fields(o).map(function(key) {
		var v = Reflect.field(o,key);
		var s = typeof(v) == "string"?thx_Strings.quote(v):thx_Dynamics.string(v);
		return "" + key + " : " + s;
	}).join(", ") + "}";
};
var thx__$Set_Set_$Impl_$ = {};
thx__$Set_Set_$Impl_$.__name__ = ["thx","_Set","Set_Impl_"];
thx__$Set_Set_$Impl_$.createString = function(it) {
	var map = new haxe_ds_StringMap();
	var set = map;
	if(null != it) thx__$Set_Set_$Impl_$.pushMany(set,it);
	return set;
};
thx__$Set_Set_$Impl_$.copy = function(this1) {
	var inst = thx__$Set_Set_$Impl_$.empty(this1);
	var tmp = this1.keys();
	while(tmp.hasNext()) {
		var k = tmp.next();
		inst.set(k,true);
	}
	return inst;
};
thx__$Set_Set_$Impl_$.empty = function(this1) {
	var inst = Type.createInstance(this1 == null?null:js_Boot.getClass(this1),[]);
	return inst;
};
thx__$Set_Set_$Impl_$.pushMany = function(this1,values) {
	var tmp = $iterator(values)();
	while(tmp.hasNext()) {
		var value = tmp.next();
		this1.set(value,true);
	}
};
thx__$Set_Set_$Impl_$.iterator = function(this1) {
	return this1.keys();
};
var thx_Strings = function() { };
thx_Strings.__name__ = ["thx","Strings"];
thx_Strings.isEmpty = function(value) {
	if(!(value == null)) return value == ""; else return true;
};
thx_Strings.quote = function(s) {
	if(s.indexOf("\"") < 0) return "\"" + s + "\""; else if(s.indexOf("'") < 0) return "'" + s + "'"; else return "\"" + StringTools.replace(s,"\"","\\\"") + "\"";
};
thx_Strings.trimCharsLeft = function(value,charlist) {
	var pos = 0;
	var _g1 = 0;
	var _g = value.length;
	while(_g1 < _g) {
		var i = _g1++;
		if(charlist.indexOf(value.charAt(i)) >= 0) ++pos; else break;
	}
	return value.substring(pos);
};
var thx_Types = function() { };
thx_Types.__name__ = ["thx","Types"];
thx_Types.sameType = function(a,b) {
	return thx_Types.toString(Type["typeof"](a)) == thx_Types.toString(Type["typeof"](b));
};
thx_Types.toString = function(type) {
	switch(type[1]) {
	case 0:
		return "Null";
	case 1:
		return "Int";
	case 2:
		return "Float";
	case 3:
		return "Bool";
	case 4:
		return "{}";
	case 5:
		return "Function";
	case 6:
		var c = type[2];
		return Type.getClassName(c);
	case 7:
		var e = type[2];
		return Type.getEnumName(e);
	default:
		throw new js__$Boot_HaxeError("invalid type " + Std.string(type));
	}
};
var thx_Uuid = function() { };
thx_Uuid.__name__ = ["thx","Uuid"];
thx_Uuid.create = function() {
	var s = [];
	var _g = 0;
	while(_g < 8) {
		var i = _g++;
		s[i] = "0123456789ABCDEF".charAt(Math.floor(Math.random() * 16));
	}
	s[8] = "-";
	var _g1 = 9;
	while(_g1 < 13) {
		var i1 = _g1++;
		s[i1] = "0123456789ABCDEF".charAt(Math.floor(Math.random() * 16));
	}
	s[13] = "-";
	s[14] = "4";
	var _g2 = 15;
	while(_g2 < 18) {
		var i2 = _g2++;
		s[i2] = "0123456789ABCDEF".charAt(Math.floor(Math.random() * 16));
	}
	s[18] = "-";
	s[19] = "89AB".charAt(Math.floor(Math.random() * 16) & 3);
	var _g3 = 20;
	while(_g3 < 23) {
		var i3 = _g3++;
		s[i3] = "0123456789ABCDEF".charAt(Math.floor(Math.random() * 16));
	}
	s[23] = "-";
	var _g4 = 24;
	while(_g4 < 36) {
		var i4 = _g4++;
		s[i4] = "0123456789ABCDEF".charAt(Math.floor(Math.random() * 16));
	}
	return s.join("");
};
var thx_error_AbstractMethod = function(posInfo) {
	thx_Error.call(this,"method " + posInfo.className + "." + posInfo.methodName + "() is abstract",null,posInfo);
};
thx_error_AbstractMethod.__name__ = ["thx","error","AbstractMethod"];
thx_error_AbstractMethod.__super__ = thx_Error;
thx_error_AbstractMethod.prototype = $extend(thx_Error.prototype,{
	__class__: thx_error_AbstractMethod
});
var thx_promise_Future = function() { };
thx_promise_Future.__name__ = ["thx","promise","Future"];
thx_promise_Future.prototype = {
	then: function(handler) {
		this.handlers.push(handler);
		this.update();
		return this;
	}
	,update: function() {
		var _g = this.state;
		switch(_g[1]) {
		case 1:
			break;
		case 0:
			var result = _g[2];
			var index = -1;
			while(true) {
				++index;
				if(!(index < this.handlers.length)) break;
				this.handlers[index](result);
			}
			this.handlers = [];
			break;
		}
	}
	,__class__: thx_promise_Future
};
var todomvc_data_Reducers = function() { };
todomvc_data_Reducers.__name__ = ["todomvc","data","Reducers"];
todomvc_data_Reducers.todoApp = function(state,action) {
	return { visibilityFilter : todomvc_data_Reducers.visibilityFilter(state.visibilityFilter,action), todos : todomvc_data_Reducers.todos(state.todos,action)};
};
todomvc_data_Reducers.todos = function(state,action) {
	switch(action[1]) {
	case 0:
		var text = action[2];
		return state.concat([{ id : thx_Uuid.create(), text : text, completed : false}]);
	case 1:
		var id = action[2];
		var index = todomvc_data_Reducers.getIndex(state,id);
		return state.slice(0,index).concat([thx_Objects.combine(state[index],{ completed : !state[index].completed})]).concat(state.slice(index + 1));
	case 2:
		var id1 = action[2];
		var index1 = todomvc_data_Reducers.getIndex(state,id1);
		return state.slice(0,index1).concat(state.slice(index1 + 1));
	case 4:
		var text1 = action[3];
		var id2 = action[2];
		var index2 = todomvc_data_Reducers.getIndex(state,id2);
		return state.slice(0,index2).concat([thx_Objects.combine(state[index2],{ text : text1})]).concat(state.slice(index2 + 1));
	case 5:
		return state.filter(function(_) {
			return !_.completed;
		});
	case 6:
		var _e = state;
		var completed = !(function(predicate) {
			return thx_Arrays.all(_e,predicate);
		})(function(_1) {
			return _1.completed;
		});
		return state.map(function(_2) {
			return { id : _2.id, text : _2.text, completed : completed};
		});
	default:
		return state;
	}
};
todomvc_data_Reducers.getIndex = function(items,id) {
	return thx_Arrays.findIndex(items,function(item) {
		return item.id == id;
	});
};
todomvc_data_Reducers.visibilityFilter = function(state,action) {
	switch(action[1]) {
	case 3:
		var filter = action[2];
		return filter;
	default:
		return state;
	}
};
var todomvc_data_TodoAction = { __ename__ : ["todomvc","data","TodoAction"], __constructs__ : ["Add","Toggle","Remove","SetVisibilityFilter","UpdateText","ClearCompleted","ToggleAll"] };
todomvc_data_TodoAction.Add = function(text) { var $x = ["Add",0,text]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.Toggle = function(id) { var $x = ["Toggle",1,id]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.Remove = function(id) { var $x = ["Remove",2,id]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.SetVisibilityFilter = function(filter) { var $x = ["SetVisibilityFilter",3,filter]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.UpdateText = function(id,text) { var $x = ["UpdateText",4,id,text]; $x.__enum__ = todomvc_data_TodoAction; $x.toString = $estr; return $x; };
todomvc_data_TodoAction.ClearCompleted = ["ClearCompleted",5];
todomvc_data_TodoAction.ClearCompleted.toString = $estr;
todomvc_data_TodoAction.ClearCompleted.__enum__ = todomvc_data_TodoAction;
todomvc_data_TodoAction.ToggleAll = ["ToggleAll",6];
todomvc_data_TodoAction.ToggleAll.toString = $estr;
todomvc_data_TodoAction.ToggleAll.__enum__ = todomvc_data_TodoAction;
var todomvc_data_VisibilityFilter = { __ename__ : ["todomvc","data","VisibilityFilter"], __constructs__ : ["ShowAll","ShowCompleted","ShowActive"] };
todomvc_data_VisibilityFilter.ShowAll = ["ShowAll",0];
todomvc_data_VisibilityFilter.ShowAll.toString = $estr;
todomvc_data_VisibilityFilter.ShowAll.__enum__ = todomvc_data_VisibilityFilter;
todomvc_data_VisibilityFilter.ShowCompleted = ["ShowCompleted",1];
todomvc_data_VisibilityFilter.ShowCompleted.toString = $estr;
todomvc_data_VisibilityFilter.ShowCompleted.__enum__ = todomvc_data_VisibilityFilter;
todomvc_data_VisibilityFilter.ShowActive = ["ShowActive",2];
todomvc_data_VisibilityFilter.ShowActive.toString = $estr;
todomvc_data_VisibilityFilter.ShowActive.__enum__ = todomvc_data_VisibilityFilter;
var todomvc_data_VisibilityFilters = function() { };
todomvc_data_VisibilityFilters.__name__ = ["todomvc","data","VisibilityFilters"];
todomvc_data_VisibilityFilters.filterVisibility = function(arr,filter) {
	switch(filter[1]) {
	case 0:
		return arr.slice();
	case 2:
		return arr.filter(function(_) {
			return !_.completed;
		});
	case 1:
		return arr.filter(function(_1) {
			return _1.completed;
		});
	}
};
var todomvc_view_App = function(props,children) {
	doom_html_Component.call(this,props,children);
};
todomvc_view_App.__name__ = ["todomvc","view","App"];
todomvc_view_App.__super__ = doom_html_Component;
todomvc_view_App.prototype = $extend(doom_html_Component.prototype,{
	render: function() {
		var _g = this;
		var bodyProps = { api : { setFilter : function(filter) {
			_g.props.dispatch(todomvc_data_TodoAction.SetVisibilityFilter(filter));
		}, clearCompleted : function() {
			_g.props.dispatch(todomvc_data_TodoAction.ClearCompleted);
		}, remove : function(id) {
			_g.props.dispatch(todomvc_data_TodoAction.Remove(id));
		}, toggle : function(id1) {
			_g.props.dispatch(todomvc_data_TodoAction.Toggle(id1));
		}, toggleAll : function() {
			_g.props.dispatch(todomvc_data_TodoAction.ToggleAll);
		}, updateText : function(id2,text) {
			_g.props.dispatch(todomvc_data_TodoAction.UpdateText(id2,text));
		}}, state : this.props.state};
		var header = new todomvc_view_Header({ add : function(text1) {
			_g.props.dispatch(todomvc_data_TodoAction.Add(text1));
		}});
		var body = new todomvc_view_Body(bodyProps);
		var f = function() {
			body.update(thx_Objects.combine(bodyProps,{ state : _g.props.state}));
		};
		this.props.subscribe(function(_,_1,_2) {
			f();
		});
		return doom_core__$VNode_VNode_$Impl_$.el("div",null,[header.asNode(),body.asNode()]);
	}
	,__class__: todomvc_view_App
});
var todomvc_view_Body = function(props,children) {
	doom_html_Component.call(this,props,children);
};
todomvc_view_Body.__name__ = ["todomvc","view","Body"];
todomvc_view_Body.__super__ = doom_html_Component;
todomvc_view_Body.prototype = $extend(doom_html_Component.prototype,{
	render: function() {
		if(this.props.state.todos.length == 0) {
			var _g = new haxe_ds_StringMap();
			var value = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("display:none");
			if(__map_reserved.style != null) _g.setReserved("style",value); else _g.h["style"] = value;
			var value1 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("nothing to do yet");
			if(__map_reserved["data-comment"] != null) _g.setReserved("data-comment",value1); else _g.h["data-comment"] = value1;
			return doom_core__$VNode_VNode_$Impl_$.el("div",_g);
		} else {
			var all = this.props.state.todos.length;
			var completed = todomvc_data_VisibilityFilters.filterVisibility(this.props.state.todos,todomvc_data_VisibilityFilter.ShowCompleted).length;
			var remaining = all - completed;
			return doom_core__$VNode_VNode_$Impl_$.el("div",null,[new todomvc_view_List({ api : this.props.api, state : { items : todomvc_data_VisibilityFilters.filterVisibility(this.props.state.todos,this.props.state.visibilityFilter), allCompleted : completed == 0}}).asNode(),new todomvc_view_Footer({ api : this.props.api, state : { remaining : remaining, filter : this.props.state.visibilityFilter, hasCompleted : completed > 0}}).asNode()]);
		}
	}
	,__class__: todomvc_view_Body
});
var todomvc_view_Footer = function(props,children) {
	doom_html_Component.call(this,props,children);
};
todomvc_view_Footer.__name__ = ["todomvc","view","Footer"];
todomvc_view_Footer.__super__ = doom_html_Component;
todomvc_view_Footer.prototype = $extend(doom_html_Component.prototype,{
	render: function() {
		var _g = new haxe_ds_StringMap();
		var value = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("todo-count");
		if(__map_reserved["class"] != null) _g.setReserved("class",value); else _g.h["class"] = value;
		var tmp = doom_core__$VNode_VNode_$Impl_$.el("span",_g,this.getItemsLeftLabel());
		var _g1 = new haxe_ds_StringMap();
		var value1 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("filters");
		if(__map_reserved["class"] != null) _g1.setReserved("class",value1); else _g1.h["class"] = value1;
		var _g5 = new haxe_ds_StringMap();
		var _g4 = new haxe_ds_StringMap();
		var value3 = this.isFilter(todomvc_data_VisibilityFilter.ShowAll);
		if(__map_reserved.selected != null) _g4.setReserved("selected",value3); else _g4.h["selected"] = value3;
		var value2 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromMap(_g4);
		if(__map_reserved["class"] != null) _g5.setReserved("class",value2); else _g5.h["class"] = value2;
		var value4 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("#");
		if(__map_reserved.href != null) _g5.setReserved("href",value4); else _g5.h["href"] = value4;
		var f = $bind(this,this.handleClickFilter);
		var value5 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromHandler(function() {
			f(todomvc_data_VisibilityFilter.ShowAll);
		});
		if(__map_reserved.click != null) _g5.setReserved("click",value5); else _g5.h["click"] = value5;
		var tmp1 = doom_core__$VNode_VNode_$Impl_$.el("li",null,[doom_core__$VNode_VNode_$Impl_$.el("a",_g5,[doom_core_VNodeImpl.Text("All")])]);
		var _g9 = new haxe_ds_StringMap();
		var _g8 = new haxe_ds_StringMap();
		var value7 = this.isFilter(todomvc_data_VisibilityFilter.ShowActive);
		if(__map_reserved.selected != null) _g8.setReserved("selected",value7); else _g8.h["selected"] = value7;
		var value6 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromMap(_g8);
		if(__map_reserved["class"] != null) _g9.setReserved("class",value6); else _g9.h["class"] = value6;
		var value8 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("#/active");
		if(__map_reserved.href != null) _g9.setReserved("href",value8); else _g9.h["href"] = value8;
		var f1 = $bind(this,this.handleClickFilter);
		var value9 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromHandler(function() {
			f1(todomvc_data_VisibilityFilter.ShowActive);
		});
		if(__map_reserved.click != null) _g9.setReserved("click",value9); else _g9.h["click"] = value9;
		var tmp2 = doom_core__$VNode_VNode_$Impl_$.el("li",null,[doom_core__$VNode_VNode_$Impl_$.el("a",_g9,[doom_core_VNodeImpl.Text("Active")])]);
		var _g13 = new haxe_ds_StringMap();
		var _g12 = new haxe_ds_StringMap();
		var value11 = this.isFilter(todomvc_data_VisibilityFilter.ShowCompleted);
		if(__map_reserved.selected != null) _g12.setReserved("selected",value11); else _g12.h["selected"] = value11;
		var value10 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromMap(_g12);
		if(__map_reserved["class"] != null) _g13.setReserved("class",value10); else _g13.h["class"] = value10;
		var value12 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("#/completed");
		if(__map_reserved.href != null) _g13.setReserved("href",value12); else _g13.h["href"] = value12;
		var f2 = $bind(this,this.handleClickFilter);
		var value13 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromHandler(function() {
			f2(todomvc_data_VisibilityFilter.ShowCompleted);
		});
		if(__map_reserved.click != null) _g13.setReserved("click",value13); else _g13.h["click"] = value13;
		var footerContent = [tmp,doom_core__$VNode_VNode_$Impl_$.el("ul",_g1,[tmp1,tmp2,doom_core__$VNode_VNode_$Impl_$.el("li",null,[doom_core__$VNode_VNode_$Impl_$.el("a",_g13,[doom_core_VNodeImpl.Text("Completed")])])])];
		if(this.props.state.hasCompleted) {
			var _g141 = new haxe_ds_StringMap();
			var value14 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("clear-completed");
			if(__map_reserved["class"] != null) _g141.setReserved("class",value14); else _g141.h["class"] = value14;
			var value15 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromHandler($bind(this,this.handleClear));
			if(__map_reserved.click != null) _g141.setReserved("click",value15); else _g141.h["click"] = value15;
			footerContent.push(doom_core__$VNode_VNode_$Impl_$.el("button",_g141,[doom_core_VNodeImpl.Text("Clear completed")]));
		}
		var _g14 = new haxe_ds_StringMap();
		var value16 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("footer");
		if(__map_reserved["class"] != null) _g14.setReserved("class",value16); else _g14.h["class"] = value16;
		return doom_core__$VNode_VNode_$Impl_$.el("footer",_g14,footerContent);
	}
	,handleClear: function() {
		this.props.api.clearCompleted();
	}
	,handleClickFilter: function(filter) {
		this.props.api.setFilter(filter);
	}
	,isFilter: function(filter) {
		return Type.enumEq(this.props.state.filter,filter);
	}
	,getItemsLeftLabel: function() {
		if(this.props.state.remaining == 1) return [doom_core__$VNode_VNode_$Impl_$.el("strong",null,[doom_core_VNodeImpl.Text("1")]),doom_core_VNodeImpl.Text(" item left")]; else return [doom_core__$VNode_VNode_$Impl_$.el("strong",null,[doom_core_VNodeImpl.Text("" + this.props.state.remaining)]),doom_core_VNodeImpl.Text(" items left")];
	}
	,__class__: todomvc_view_Footer
});
var todomvc_view_Header = function(props,children) {
	doom_html_Component.call(this,props,children);
};
todomvc_view_Header.__name__ = ["todomvc","view","Header"];
todomvc_view_Header.__super__ = doom_html_Component;
todomvc_view_Header.prototype = $extend(doom_html_Component.prototype,{
	render: function() {
		var _g = new haxe_ds_StringMap();
		var value = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("header");
		if(__map_reserved["class"] != null) _g.setReserved("class",value); else _g.h["class"] = value;
		var tmp = doom_core__$VNode_VNode_$Impl_$.el("h1",null,[doom_core_VNodeImpl.Text("todos")]);
		var _g1 = new haxe_ds_StringMap();
		var value1 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("new-todo");
		if(__map_reserved["class"] != null) _g1.setReserved("class",value1); else _g1.h["class"] = value1;
		var value2 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("What needs to be done?");
		if(__map_reserved.placeholder != null) _g1.setReserved("placeholder",value2); else _g1.h["placeholder"] = value2;
		var value3 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromBool(true);
		if(__map_reserved.autofocus != null) _g1.setReserved("autofocus",value3); else _g1.h["autofocus"] = value3;
		var value4 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromEventHandler($bind(this,this.handleKeys));
		if(__map_reserved.keydown != null) _g1.setReserved("keydown",value4); else _g1.h["keydown"] = value4;
		return doom_core__$VNode_VNode_$Impl_$.el("header",_g,[tmp,doom_core__$VNode_VNode_$Impl_$.el("input",_g1,null)]);
	}
	,handleKeys: function(e) {
		if(13 == e.which) {
			e.preventDefault();
			var value = this.getInputValueAndEmpty();
			if(thx_Strings.isEmpty(value)) return;
			this.props.add(value);
		}
	}
	,getInputValueAndEmpty: function() {
		var el = this.node.querySelector("input");
		var value = StringTools.trim(el.value);
		el.value = "";
		return value;
	}
	,__class__: todomvc_view_Header
});
var todomvc_view_Item = function(props,children) {
	doom_html_Component.call(this,props,children);
};
todomvc_view_Item.__name__ = ["todomvc","view","Item"];
todomvc_view_Item.__super__ = doom_html_Component;
todomvc_view_Item.prototype = $extend(doom_html_Component.prototype,{
	render: function() {
		var _g1 = new haxe_ds_StringMap();
		var _g = new haxe_ds_StringMap();
		var value1 = this.props.state.item.completed;
		if(__map_reserved.completed != null) _g.setReserved("completed",value1); else _g.h["completed"] = value1;
		var value2 = this.props.state.editing;
		if(__map_reserved.editing != null) _g.setReserved("editing",value2); else _g.h["editing"] = value2;
		var value = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromMap(_g);
		if(__map_reserved["class"] != null) _g1.setReserved("class",value); else _g1.h["class"] = value;
		var value3 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromHandler($bind(this,this.handleDblClick));
		if(__map_reserved.dblclick != null) _g1.setReserved("dblclick",value3); else _g1.h["dblclick"] = value3;
		var _g2 = new haxe_ds_StringMap();
		var value4 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("view");
		if(__map_reserved["class"] != null) _g2.setReserved("class",value4); else _g2.h["class"] = value4;
		var _g3 = new haxe_ds_StringMap();
		var value5 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("toggle");
		if(__map_reserved["class"] != null) _g3.setReserved("class",value5); else _g3.h["class"] = value5;
		var value6 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("checkbox");
		if(__map_reserved.type != null) _g3.setReserved("type",value6); else _g3.h["type"] = value6;
		var value7 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromBool(this.props.state.item.completed);
		if(__map_reserved.checked != null) _g3.setReserved("checked",value7); else _g3.h["checked"] = value7;
		var value8 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromHandler(($_=this.props.api,$bind($_,$_.toggle)));
		if(__map_reserved.change != null) _g3.setReserved("change",value8); else _g3.h["change"] = value8;
		var tmp = doom_core__$VNode_VNode_$Impl_$.el("input",_g3,null);
		var tmp1 = doom_core__$VNode_VNode_$Impl_$.el("label",null,[doom_core_VNodeImpl.Text(this.props.state.item.text)]);
		var _g4 = new haxe_ds_StringMap();
		var value9 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("destroy");
		if(__map_reserved["class"] != null) _g4.setReserved("class",value9); else _g4.h["class"] = value9;
		var value10 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromHandler(($_=this.props.api,$bind($_,$_.remove)));
		if(__map_reserved.click != null) _g4.setReserved("click",value10); else _g4.h["click"] = value10;
		var tmp2 = doom_core__$VNode_VNode_$Impl_$.el("div",_g2,[tmp,tmp1,doom_core__$VNode_VNode_$Impl_$.el("button",_g4,null)]);
		var _g5 = new haxe_ds_StringMap();
		var value11 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("edit");
		if(__map_reserved["class"] != null) _g5.setReserved("class",value11); else _g5.h["class"] = value11;
		var value12 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString(this.props.state.item.text);
		if(__map_reserved.value != null) _g5.setReserved("value",value12); else _g5.h["value"] = value12;
		var value13 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromHandler($bind(this,this.handleBlur));
		if(__map_reserved.blur != null) _g5.setReserved("blur",value13); else _g5.h["blur"] = value13;
		var value14 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromEventHandler($bind(this,this.handleKeydown));
		if(__map_reserved.keyup != null) _g5.setReserved("keyup",value14); else _g5.h["keyup"] = value14;
		return doom_core__$VNode_VNode_$Impl_$.el("li",_g1,[tmp2,doom_core__$VNode_VNode_$Impl_$.el("input",_g5,null)]);
	}
	,handleDblClick: function() {
		this.props.state.editing = true;
		this.update(this.props);
		this.getInput().select();
	}
	,handleBlur: function() {
		if(!this.props.state.editing) return;
		this.props.state.editing = false;
		var value = this.getInputValueAndTrim();
		if(thx_Strings.isEmpty(value)) this.props.api.remove(); else if(value != this.props.state.item.text) this.props.api.updateText(value); else this.update(thx_Objects.combine(this.props,{ state : { item : this.props.state.item, editing : false}}));
	}
	,handleKeydown: function(e) {
		if(e.which != 13) return;
		this.handleBlur();
	}
	,getInput: function() {
		return this.node.querySelector("input.edit");
	}
	,getInputValueAndTrim: function() {
		var input = this.getInput();
		return input.value = StringTools.trim(input.value);
	}
	,__class__: todomvc_view_Item
});
var todomvc_view_List = function(props,children) {
	doom_html_Component.call(this,props,children);
};
todomvc_view_List.__name__ = ["todomvc","view","List"];
todomvc_view_List.__super__ = doom_html_Component;
todomvc_view_List.prototype = $extend(doom_html_Component.prototype,{
	render: function() {
		var _g = new haxe_ds_StringMap();
		var value = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("main");
		if(__map_reserved["class"] != null) _g.setReserved("class",value); else _g.h["class"] = value;
		var _g1 = new haxe_ds_StringMap();
		var value1 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("toggle-all");
		if(__map_reserved["class"] != null) _g1.setReserved("class",value1); else _g1.h["class"] = value1;
		var value2 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("checkbox");
		if(__map_reserved.type != null) _g1.setReserved("type",value2); else _g1.h["type"] = value2;
		var value3 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromBool(this.props.state.allCompleted);
		if(__map_reserved.checked != null) _g1.setReserved("checked",value3); else _g1.h["checked"] = value3;
		var value4 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromHandler(($_=this.props.api,$bind($_,$_.toggleAll)));
		if(__map_reserved.change != null) _g1.setReserved("change",value4); else _g1.h["change"] = value4;
		var tmp = doom_core__$VNode_VNode_$Impl_$.el("input",_g1,null);
		var _g2 = new haxe_ds_StringMap();
		var value5 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("toggle-all");
		if(__map_reserved["for"] != null) _g2.setReserved("for",value5); else _g2.h["for"] = value5;
		var tmp1 = doom_core__$VNode_VNode_$Impl_$.el("label",_g2,[doom_core_VNodeImpl.Text("Mark all as complete")]);
		var _g3 = new haxe_ds_StringMap();
		var value6 = doom_core__$AttributeValue_AttributeValue_$Impl_$.fromString("todo-list");
		if(__map_reserved["class"] != null) _g3.setReserved("class",value6); else _g3.h["class"] = value6;
		var _g4 = [];
		var tmp2 = HxOverrides.iter(this.props.state.items);
		while(tmp2.hasNext()) {
			var item = tmp2.next();
			_g4.push(new todomvc_view_Item({ api : { remove : (function(id,f) {
				return function() {
					f[0](id[0]);
				};
			})([item.id],[($_=this.props.api,$bind($_,$_.remove))]), toggle : (function(id1,f1) {
				return function() {
					f1[0](id1[0]);
				};
			})([item.id],[($_=this.props.api,$bind($_,$_.toggle))]), updateText : (function(id2,f2) {
				return function(a1) {
					f2[0](id2[0],a1);
				};
			})([item.id],[($_=this.props.api,$bind($_,$_.updateText))])}, state : { item : item, editing : false}}).asNode());
		}
		return doom_core__$VNode_VNode_$Impl_$.el("section",_g,[tmp,tmp1,doom_core__$VNode_VNode_$Impl_$.el("ul",_g3,_g4)]);
	}
	,__class__: todomvc_view_List
});
function $iterator(o) { if( o instanceof Array ) return function() { return HxOverrides.iter(o); }; return typeof(o.iterator) == 'function' ? $bind(o,o.iterator) : o.iterator; }
var $_, $fid = 0;
function $bind(o,m) { if( m == null ) return null; if( m.__id__ == null ) m.__id__ = $fid++; var f; if( o.hx__closures__ == null ) o.hx__closures__ = {}; else f = o.hx__closures__[m.__id__]; if( f == null ) { f = function(){ return f.method.apply(f.scope, arguments); }; f.scope = o; f.method = m; o.hx__closures__[m.__id__] = f; } return f; }
if(Array.prototype.indexOf) HxOverrides.indexOf = function(a,o,i) {
	return Array.prototype.indexOf.call(a,o,i);
};
String.prototype.__class__ = String;
String.__name__ = ["String"];
Array.__name__ = ["Array"];
Date.prototype.__class__ = Date;
Date.__name__ = ["Date"];
var Int = { __name__ : ["Int"]};
var Dynamic = { __name__ : ["Dynamic"]};
var Float = Number;
Float.__name__ = ["Float"];
var Bool = Boolean;
Bool.__ename__ = ["Bool"];
var Class = { __name__ : ["Class"]};
var Enum = { };
if(Array.prototype.map == null) Array.prototype.map = function(f) {
	var a = [];
	var _g1 = 0;
	var _g = this.length;
	while(_g1 < _g) {
		var i = _g1++;
		a[i] = f(this[i]);
	}
	return a;
};
if(Array.prototype.filter == null) Array.prototype.filter = function(f1) {
	var a1 = [];
	var _g11 = 0;
	var _g2 = this.length;
	while(_g11 < _g2) {
		var i1 = _g11++;
		var e = this[i1];
		if(f1(e)) a1.push(e);
	}
	return a1;
};
var __map_reserved = {}
var ArrayBuffer = $global.ArrayBuffer || js_html_compat_ArrayBuffer;
if(ArrayBuffer.prototype.slice == null) ArrayBuffer.prototype.slice = js_html_compat_ArrayBuffer.sliceImpl;
var Uint8Array = $global.Uint8Array || js_html_compat_Uint8Array._new;

      // Production steps of ECMA-262, Edition 5, 15.4.4.21
      // Reference: http://es5.github.io/#x15.4.4.21
      if (!Array.prototype.reduce) {
        Array.prototype.reduce = function(callback /*, initialValue*/) {
          'use strict';
          if (this == null) {
            throw new TypeError('Array.prototype.reduce called on null or undefined');
          }
          if (typeof callback !== 'function') {
            throw new TypeError(callback + ' is not a function');
          }
          var t = Object(this), len = t.length >>> 0, k = 0, value;
          if (arguments.length == 2) {
            value = arguments[1];
          } else {
            while (k < len && ! k in t) {
              k++;
            }
            if (k >= len) {
              throw new TypeError('Reduce of empty array with no initial value');
            }
            value = t[k++];
          }
          for (; k < len; k++) {
            if (k in t) {
              value = callback(value, t[k], k, t);
            }
          }
          return value;
        };
      }
    ;
doom_html_Render.defaultNamespaces = (function($this) {
	var $r;
	var _g = new haxe_ds_StringMap();
	if(__map_reserved.svg != null) _g.setReserved("svg","http://www.w3.org/2000/svg"); else _g.h["svg"] = "http://www.w3.org/2000/svg";
	$r = _g;
	return $r;
}(this));
Doom.browser = new doom_html_Render();
doom_html_Attributes.properties = (function($this) {
	var $r;
	var _g = new haxe_ds_StringMap();
	{
		var value = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.allowFullScreen != null) _g.setReserved("allowFullScreen",value); else _g.h["allowFullScreen"] = value;
	}
	{
		var value1 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.async != null) _g.setReserved("async",value1); else _g.h["async"] = value1;
	}
	{
		var value2 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.autoFocus != null) _g.setReserved("autoFocus",value2); else _g.h["autoFocus"] = value2;
	}
	{
		var value3 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.autoPlay != null) _g.setReserved("autoPlay",value3); else _g.h["autoPlay"] = value3;
	}
	{
		var value4 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.capture != null) _g.setReserved("capture",value4); else _g.h["capture"] = value4;
	}
	{
		var value5 = doom_html_AttributeType.BooleanProperty;
		if(__map_reserved.checked != null) _g.setReserved("checked",value5); else _g.h["checked"] = value5;
	}
	{
		var value6 = doom_html_AttributeType.PositiveNumericAttribute;
		if(__map_reserved.cols != null) _g.setReserved("cols",value6); else _g.h["cols"] = value6;
	}
	{
		var value7 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.controls != null) _g.setReserved("controls",value7); else _g.h["controls"] = value7;
	}
	{
		var value8 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved["default"] != null) _g.setReserved("default",value8); else _g.h["default"] = value8;
	}
	{
		var value9 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.defer != null) _g.setReserved("defer",value9); else _g.h["defer"] = value9;
	}
	{
		var value10 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.disabled != null) _g.setReserved("disabled",value10); else _g.h["disabled"] = value10;
	}
	{
		var value11 = doom_html_AttributeType.OverloadedBooleanAttribute;
		if(__map_reserved.download != null) _g.setReserved("download",value11); else _g.h["download"] = value11;
	}
	{
		var value12 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.formNoValidate != null) _g.setReserved("formNoValidate",value12); else _g.h["formNoValidate"] = value12;
	}
	{
		var value13 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.hidden != null) _g.setReserved("hidden",value13); else _g.h["hidden"] = value13;
	}
	{
		var value14 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.loop != null) _g.setReserved("loop",value14); else _g.h["loop"] = value14;
	}
	{
		var value15 = doom_html_AttributeType.BooleanProperty;
		if(__map_reserved.multiple != null) _g.setReserved("multiple",value15); else _g.h["multiple"] = value15;
	}
	{
		var value16 = doom_html_AttributeType.BooleanProperty;
		if(__map_reserved.muted != null) _g.setReserved("muted",value16); else _g.h["muted"] = value16;
	}
	{
		var value17 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.noValidate != null) _g.setReserved("noValidate",value17); else _g.h["noValidate"] = value17;
	}
	{
		var value18 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.open != null) _g.setReserved("open",value18); else _g.h["open"] = value18;
	}
	{
		var value19 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.readOnly != null) _g.setReserved("readOnly",value19); else _g.h["readOnly"] = value19;
	}
	{
		var value20 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.required != null) _g.setReserved("required",value20); else _g.h["required"] = value20;
	}
	{
		var value21 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.reversed != null) _g.setReserved("reversed",value21); else _g.h["reversed"] = value21;
	}
	{
		var value22 = doom_html_AttributeType.PositiveNumericAttribute;
		if(__map_reserved.rows != null) _g.setReserved("rows",value22); else _g.h["rows"] = value22;
	}
	{
		var value23 = doom_html_AttributeType.NumericAttribute;
		if(__map_reserved.rowSpan != null) _g.setReserved("rowSpan",value23); else _g.h["rowSpan"] = value23;
	}
	{
		var value24 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.scoped != null) _g.setReserved("scoped",value24); else _g.h["scoped"] = value24;
	}
	{
		var value25 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.seamless != null) _g.setReserved("seamless",value25); else _g.h["seamless"] = value25;
	}
	{
		var value26 = doom_html_AttributeType.BooleanProperty;
		if(__map_reserved.selected != null) _g.setReserved("selected",value26); else _g.h["selected"] = value26;
	}
	{
		var value27 = doom_html_AttributeType.PositiveNumericAttribute;
		if(__map_reserved.size != null) _g.setReserved("size",value27); else _g.h["size"] = value27;
	}
	{
		var value28 = doom_html_AttributeType.PositiveNumericAttribute;
		if(__map_reserved.span != null) _g.setReserved("span",value28); else _g.h["span"] = value28;
	}
	{
		var value29 = doom_html_AttributeType.NumericAttribute;
		if(__map_reserved.start != null) _g.setReserved("start",value29); else _g.h["start"] = value29;
	}
	{
		var value30 = doom_html_AttributeType.SideEffectProperty;
		if(__map_reserved.value != null) _g.setReserved("value",value30); else _g.h["value"] = value30;
	}
	{
		var value31 = doom_html_AttributeType.BooleanAttribute;
		if(__map_reserved.itemScope != null) _g.setReserved("itemScope",value31); else _g.h["itemScope"] = value31;
	}
	$r = _g;
	return $r;
}(this));
dots_Html.pattern = new EReg("[<]([^> ]+)","");
dots_Query.doc = document;
haxe_ds_ObjectMap.count = 0;
js_Boot.__toStr = {}.toString;
js_html_compat_Uint8Array.BYTES_PER_ELEMENT = 1;
Main.main();
})(typeof console != "undefined" ? console : {log:function(){}}, typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this);
